### PR TITLE
fix(types): remove kdljs typescript namespace

### LINKED ISSUE #19: export Node type: Namespace has no exported member 'Node'
I'm writing a function in my app to map from generic KDL Node types to my app's specific type:

```ts
function nodeToItem(node: kdljs.Node, _index?: number, _array?: kdljs.Node[]): Item {
  return {
    label: node.name,
    run: node.values.map((v)=>String(v)),
    key: node.properties && String(node.properties.key) ,
    items: node.children.map(nodeToItem),
  };
}
```

But typescript is complaining that the `Node` type is not exported.

```
Namespace '"...../node_modules/kdljs/index"' has no exported member 'Node'.
```

I'm new to typescript so apologies if this is my misunderstanding, but I'm told if kdjls exported the Node type, I could directly use it. For now my workaround is to get access to the type via introspection into the kdljs.format function parameters.

```ts
type Node = Parameters<typeof kdljs.format>[0][number]
```

### PR DESCRIPTION
**Pull request by focusaurus**
Fixes #19

Breaking change for typescript users.

---

This diff may look big but it is only 2 logical changes:

1. Remove the outer kdljs namespace block & dedent the code accordingly
2. Delete all references to the `kdljs.' namespace

Line 80 got 2 other changes because I formatted with prettier but they seem better to me. Happy to go into "change the fewest bytes possible" mode if anyone is fussy about PRs that way here.

The unit tests still pass fine and my project compiles fine under typescript with this change. The big caveat here is that I am a typescript novice so not confident about this change.

This change I think would count as a bugfix for JS users but would be considered breaking for TS users, and I don't know what the means for semver and changelog purposes. My suspicion is I am one of a very small number of users of both kdljs with typescript at the moment.

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -1,93 +1,91 @@
...
  */
-export function parse(text: string): kdljs.ParseResult;
+export function parse(text: string): ParseResult;
 
 /**
- * @param {kdljs.Document} doc - Input KDL document
+ * @param {Document} doc - Input KDL document
  */
-export function format(doc: kdljs.Document, options?: kdljs.FormattingOptions): string;
+export function format( doc: Document, options?: FormattingOptions,): string;
```
Comment (larsgw) [inline index.d.ts:80]: Why the space and trailing comma here?

Comment (focusaurus) [reply index.d.ts]: Not sure. I re-ran prettier and it cleaned them up though.
